### ISSUE TITLE
Virus detected on download of bladebit-v2.0.0-rc1-windows-x86-64.zip

### ISSUE THREAD

**Issue by Drhicom** [Chia-Network/bladebit#234]
![image](https://user-images.githubusercontent.com/81637574/199345774-0c003c13-64ba-4cec-8984-fcc7c2b0c684.png)

Can somebody please check this out?

**Comment by harold-b** [comment]
Investigating now

**Comment by Drhicom** [comment]
Did you find out anything yet, Do I need the can of RAID???

**Comment by justinengland** [comment]
Hello! Apologies for this! 

This appears to be a very nasty bug, on the Github end. We are currently investigating this issue with our support team. 

Wecurrently do not believe this to be a compromise of the supply chain or the code base in question, however just to be safe, hold off running any artifacts from this repo till we confirm this with our providers. 

We have an open dialogue with our Github team and we are actively engaged on finding the root cause of this bug. 

I will post here with the findings of our investigation once we have more clear data to provide to you. 

Please be patient this might take several hours to get good information back to you. We are actively working the issue and I will report here as soon as we have more to share. 

Best, 

Justin 
VP of Platform and Security

**Comment by Jacek-ghub** [comment]
@justinengland Could you add to 'What's Changed" section that the builds are not available, and you are working to resolve it.  

Also, as the culprit is still unknown maybe all assets should be suppressed, not just Win build.

**Comment by harold-b** [comment]
We was able to reproduce the alert yesterday on Brave on Windows only. Brave on macOS or other browsers were not reproducing this alert. We scanned the archive and it yield no threats. Everything still points to a false positive but we were (and still are) being thorough to ensure all is fine. We also extracted the archive and downloaded the exe in a machine that was able to reproduce, and that too yielded no alerts.

Today I am not able to reproduce the issue with the same archive. The windows machine that reproduced this before updated its protection intelligence today to version `1.377.1214.0` so it may not detecting the false positive anymore. 

@Drhicom Can you do a test yourself by attempting to download the archive from the CI build that generated the one attached to the release here: https://github.com/Chia-Network/bladebit/actions/runs/3363830998

The artifacts are found in the bottom of the page. You can attempt to download the windows zip file to see if that still alerts you. It does not alert for me anymore (still the same archive).

**Comment by Jacek-ghub** [comment]
On Edge - no threat detected (was there yesterday)
On FireFox - none of the files have downloadable links (no <a href=...> in the HTML file)

**Comment by harold-b** [comment]
> On FireFox - none of the files have downloadable links (no [in the HTML file)](https://github.com/Chia-Network/bladebit/issues/...)
You need to be logged-in to github to be able to download the artifacts from a CI run

**Comment by Jacek-ghub** [comment]
I am logged in in both, although with different user names.

**Comment by harold-b** [comment]
I see, not quite sure would be the problem in that case

**Comment by Jacek-ghub** [comment]
The easiest way to check it is for you to use FF

**Comment by justinengland** [comment]
Hey All! 

We have heard back from Github and they have confirmed that this was a false positive.

We are continuing investigation of the root cause for this incident, it is likely some form of flaking on the build time environment and a false positive from the virus scanners at play. 

Apologies for the issue, and for how frightening this might have been. 

I will respond here with the root cause once we have it, for posterity. 

Best, 

Justin

**Comment by Drhicom** [comment]
I was able to click on the link
https://github.com/Chia-Network/bladebit/actions/runs/3363830998
That Harold provided and at the bottom I download the file and put it on another test node.

Thanks again

Roy

**Comment by harold-b** [comment]
Thanks for validating @Drhicom and @Jacek-ghub

**Comment by Jacek-ghub** [comment]
> I will respond here with the root cause once we have it, for posterity.

@justinengland 

There are only four people participating in this thread (sure, more just read it without participating).  From my point of view, I would be interested in knowing what happened.  I would also like to have you to ask Github to let you contact other github members that experienced the same problem, so you could verify what Github is saying.  Otherwise, I would assume that Github is just trying to get off the hook as fast as possible.

However, I would assume that more serious actions will be taken.  We can assume that compromising Chia builds or source code could result in plenty of warm wallets being emptied, as it just takes a couple of RPC calls on the node to get active mnemonics, and have full access to the wallet.

It is kind of a surprise to see Chia blog about protecting pre-farm, while not making the bare minimum efforts to checks on provided downloads.  Chia does not release new versions every other day, so it is really surprising that before making those downloads available, no browsers / platforms were checked.  Potentially, the code integrity is also not checked.  There is also no checksum provided on those builds, what is basically a software malpractice.

**Comment by justinengland** [comment]
Hello! 

Rest assured that the appropriate amount of rigor is being applied from our end. 

Let me start with an appreciation for the healthy skepticism being shown here. 

I can say for sure though that your assumption about what this issue was, and what steps we take to mitigate concerns like this are way off base. 

Your assertion of what the issues at hand in no way represents how we are handling this issue, nor does it capture the actual circumstances of the issue. 

There was no injection into our code base, there was no injection of malicious code into the installer, There was no injection into any portion of this supply chain. The error reported was a false positive, this is actually very common with certain types of virus scanning tools. This was a bug somewhere on the Github end that was fuzzing the zipped file just enough to trip the antivirus scanning.

I understand this on its face appears to be a very frightening thing to have happened, I can assure you, with 100% certainty, that this is a nothing issue. There was no actual incident. 

The best part is, you don't have to believe me! You can fork the repo and run the build time on your own runners. Or pull the repo down and build it locally. 

Thank you for commenting, but I do ask that you refrain from accusing Chia Network Inc, or myself of lapses in our security posture without any backing evidence. 

It is absolutely your right to be worried about warnings like occurred in this bug. It is not however fair to assume the people working on it on this end aren't doing our diligence.

To explain more clearly what we are actually discussing here. These are not downloads provided as official chia releases, these are dev builds from a repo that is actively under development. There will be bugs in beta builds, this one was a nasty scary one but in the end harmless. These artifacts do however run through the full CI and testing suite that is part of all of our operations here at Chia. We run build, scan and test logic, the last portion is a Github provided action that does the tarring and or zipping of the asset and then uploads it to the package store that then makes the file availabe on Github. 

The last mile in this instance is all provided by the Github platform. 

If github uploads were compromised globally, I assure you we would know. As with any system there can be bugs. It is actually very common to get false alarms like this. Especially when compacting files. 

Thank you, 

Justin

**Comment by Jacek-ghub** [comment]
Just to clarify.  I didn't say that injection was there or at this point could be.  I stated that if someone would be interesting in attacking Chia ecosystem, this may be a viable vector for doing it in the future, so extra care may be needed to be protected from it (e.g., hash for each build, testing downloads using popular platforms / browsers).  Nothing more than that.

I think it is well understood by now that this was a false positive, still I would try to push Github for those references.  Also, I would assume that with all the testing you have in place that false positive would be caught before making the download available to the public.  As you stated it was a scary one, at least to some of us.
