### ISSUE TITLE
Start creating new Plot regardless of the transfer process to HDD.

### ISSUE THREAD

**Issue by fabgsouza76** [Chia-Network/bladebit#73]
I can create PLOTS within 400sec on my system but it takes longer to transfer to HDD due to HDD speed. 
Is there a way for it to do like MADMAX and start the creation of a new PLOT but the transfer/copy process keeps running on the background until is done?
Please advise.
A temp HDD/SSD for it as suggested before would be a good solution too.

**Comment by harold-b** [comment]
The only way to do this would be to allocated more memory for the buffers that are being written in the background, and even then, if the writes are not fast enough, and your 2nd+ plots might stall because the buffers are still busy.

Your best bet is to use NVMe's as the output drive then move them over to HDD's when finished (as original intended) as @xorinox explains here:

https://chiaforum.com/t/bladebit-plotting-at-220-280-plots-per-day-on-one-system/11987

**Comment by preutrn** [comment]
Is there any plans to allow for additional buffers allocation? It'd be cool to plot directly to spinning drives ditching NVMe wear.

**Comment by jmhands** [comment]
many scripts to automate plot moving, closing
